/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PhotographerRouteImport } from './routes/photographer'
import { Route as PhotographersRouteImport } from './routes/photographers'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PackagesPackageIdRouteImport } from './routes/packages.$packageId'
import { Route as PhotographersPhotographerIdRouteImport } from './routes/photographers.$photographerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographerRoute = PhotographerRouteImport.update({
  id: '/photographer',
  path: '/photographer',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographersRoute = PhotographersRouteImport.update({
  id: '/photographers',
  path: '/photographers',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesPackageIdRoute = PackagesPackageIdRouteImport.update({
  id: '/$packageId',
  path: '/$packageId',
  getParentRoute: () => PackagesRoute,
} as any)
const PhotographersPhotographerIdRoute =
  PhotographersPhotographerIdRouteImport.update({
    id: '/$photographerId',
    path: '/$photographerId',
    getParentRoute: () => PhotographersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRouteWithChildren
  '/photographer': typeof PhotographerRoute
  '/photographers': typeof PhotographersRouteWithChildren
  '/register': typeof RegisterRoute
  '/packages/$packageId': typeof PackagesPackageIdRoute
  '/photographers/$photographerId': typeof PhotographersPhotographerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRouteWithChildren
  '/photographer': typeof PhotographerRoute
  '/photographers': typeof PhotographersRouteWithChildren
  '/register': typeof RegisterRoute
  '/packages/$packageId': typeof PackagesPackageIdRoute
  '/photographers/$photographerId': typeof PhotographersPhotographerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRouteWithChildren
  '/photographer': typeof PhotographerRoute
  '/photographers': typeof PhotographersRouteWithChildren
  '/register': typeof RegisterRoute
  '/packages/$packageId': typeof PackagesPackageIdRoute
  '/photographers/$photographerId': typeof PhotographersPhotographerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book'
    | '/dashboard'
    | '/login'
    | '/packages'
    | '/photographer'
    | '/photographers'
    | '/register'
    | '/packages/$packageId'
    | '/photographers/$photographerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/book'
    | '/dashboard'
    | '/login'
    | '/packages'
    | '/photographer'
    | '/photographers'
    | '/register'
    | '/packages/$packageId'
    | '/photographers/$photographerId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book'
    | '/dashboard'
    | '/login'
    | '/packages'
    | '/photographer'
    | '/photographers'
    | '/register'
    | '/packages/$packageId'
    | '/photographers/$photographerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookRoute: typeof BookRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  PhotographerRoute: typeof PhotographerRoute
  PhotographersRoute: typeof PhotographersRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographer': {
      id: '/photographer'
      path: '/photographer'
      fullPath: '/photographer'
      preLoaderRoute: typeof PhotographerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photographers': {
      id: '/photographers'
      path: '/photographers'
      fullPath: '/photographers'
      preLoaderRoute: typeof PhotographersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$packageId': {
      id: '/packages/$packageId'
      path: '/$packageId'
      fullPath: '/packages/$packageId'
      preLoaderRoute: typeof PackagesPackageIdRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/photographers/$photographerId': {
      id: '/photographers/$photographerId'
      path: '/$photographerId'
      fullPath: '/photographers/$photographerId'
      preLoaderRoute: typeof PhotographersPhotographerIdRouteImport
      parentRoute: typeof PhotographersRoute
    }
  }
}

interface PackagesRouteChildren {
  PackagesPackageIdRoute: typeof PackagesPackageIdRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesPackageIdRoute: PackagesPackageIdRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

interface PhotographersRouteChildren {
  PhotographersPhotographerIdRoute: typeof PhotographersPhotographerIdRoute
}

const PhotographersRouteChildren: PhotographersRouteChildren = {
  PhotographersPhotographerIdRoute: PhotographersPhotographerIdRoute,
}

const PhotographersRouteWithChildren = PhotographersRoute._addFileChildren(
  PhotographersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookRoute: BookRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRouteWithChildren,
  PhotographerRoute: PhotographerRoute,
  PhotographersRoute: PhotographersRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
